# Include config file
configfile: "config.yaml"

# Finish rule collecting all desired output.
rule finish:
    input:
        os.path.join(config['output_dir'],"hello_output_1.txt"),
        os.path.join(config['output_dir'],"hello_output_2.txt")

include: "rules.smk"

rule hello_world_2:
    input:
        config['an_input']
    output:
        os.path.join(config['output_dir'],"hello_output_2.txt")
    log:
        os.path.join(config['output_dir'],"output_2.log")
    container: 
        "docker://ubuntu:22.04"
    shell:
        """
        exec > {log} 2>&1
        echo "Hello world 2!!!!!!!" > {output} 
        echo
        echo "Computing the md5 of {input}" 
        md5sum {input} 
        echo
        echo "Showing the inherited environment"
        env
        """